@baseUrl = http://localhost:3000/api/v1

### Health check
GET {{baseUrl}}/health

### 401 - operational error
GET {{baseUrl}}/error/unauthorized

### 500 - non-operational (message hidden in prod)
GET {{baseUrl}}/error/crash

### 500 - raw programmer error
GET {{baseUrl}}/error/unhandled

### 404 - not found handler
GET {{baseUrl}}/does-not-exist